#指定程序的启动端口  
server:
  port: 8604

#指定使用的环境配置文件、程序名
spring:
  profiles:
    active: prod
  application: 
    name: omdsSdxl

#指定eureka服务注册地址  
eureka: 
  client:
    serviceUrl: 
      defaultZone: http://localhost:8901/eureka

#mybatis config
mybatis: 
  typeAliasesPackage: com.jydw.entity
  mapperLocations: classpath:mapper_oracle/*/*/*.xml

#日志
logging:
  level:
     com.jydw.sdxl : debug  
#变量
foo: omdsSdxl-prod配置文件   